#!/bin/sh

# PROVIDE: bates
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="bates"
rcvar=${name}_enable

load_rc_config $name

# : ${bates_enable="NO"}

start_cmd="start"
stop_cmd="stop"
restart_cmd="restart"

restas_dir="/usr/local/etc/restas"
sbcl_bin="/usr/local/bin/sbcl"
sbcl_cmd="${sbcl_bin} --noinform --no-userinit --no-sysinit --load ${restas_dir}/restas-daemon.lisp ${restas_dir}/${name}.conf"


start()
{
    ${sbcl_cmd} start
}

stop()
{
    ${sbcl_cmd} stop
}

restart()
{
    ${sbcl_cmd} restart
}

run_rc_command "$1"

